/* ═══════════════════════════════════════════════════════════════
   NectarOS  —  i18n Language Pack  v1.0
   Languages: ar | en | fr | tr | es | de | it | nl
   © 2025 BENADLA MOHAMMED AMINE
═══════════════════════════════════════════════════════════════ */

const NECTAR_LANGS = {

/* ─────────────────────────────────────────────────────────────
   🇩🇿  ARABIC  (default / base)
───────────────────────────────────────────────────────────── */
ar: {
  _dir:'rtl', _name:'العربية', _flag:'🇩🇿',

  /* App shell */
  app_name:'NectarOS', app_sub:'نظام إدارة المناحل الذكي',
  loading:'جاري التحميل',

  /* Update banner */
  update_available:'🎉 إصدار جديد متاح — اضغط لتحديث التطبيق',
  update_safe:'بياناتك محفوظة بأمان',
  update_btn:'⬆️ تحديث',

  /* License screen */
  lic_title:'NectarOS', lic_sub:'نظام الترخيص',
  lic_tab_trial:'⏱️ التجربة', lic_tab_activate:'🔑 تفعيل', lic_tab_devices:'📱 الأجهزة',
  lic_extend_trial:'⏳ تمديد التجربة 15 يوم إضافياً',
  lic_enter_app:'🐝 دخول التطبيق',
  lic_device_hint:'🔑 معرّف جهازك (أرسله للمطوّر للحصول على السيريال)',
  lic_copy_device:'📋 نسخ معرّف الجهاز',
  lic_serial_label:'أدخل رمز التفعيل (Serial)',
  lic_serial_placeholder:'XXXX-XXXX-XXXX-XXXX',
  lic_activate_btn:'✅ تفعيل الترخيص',
  lic_buy_title:'🛒 كيف تشتري الترخيص؟',
  lic_buy_step1:'انسخ معرّف جهازك من الأعلى',
  lic_buy_step2:'أرسله مع الدفع عبر إحدى الطرق أدناه',
  lic_buy_step3:'ستصلك رمز التفعيل خلال 24 ساعة',
  lic_wa_btn:'💬 تواصل معنا عبر واتساب',
  lic_wa_hint:'أرسل معرّف جهازك وإيصال الدفع لتفعيل ترخيصك',

  /* Trial */
  trial_active:'تجريبي نشط', trial_expired:'منتهي',
  trial_days_left:'يوم متبقٍ', trial_total_days:'إجمالي الأيام',
  trial_extension:'تمديد',
  trial_almost_up:'الوقت ينفد!',
  trial_few_days:'أيام قليلة متبقية',
  trial_mode:'وضع تجريبي',
  trial_elapsed:'مضت',
  trial_of:'من أصل',
  trial_activate_now:'⚡ فعّل الترخيص قبل انتهاء الوقت',
  trial_data_safe:'بياناتك محفوظة وستنتقل للنسخة المدفوعة تلقائياً',
  trial_used:'تم الاستخدام', trial_available:'متاح',
  trial_ended_title:'انتهت فترة التجربة!',
  trial_ended_sub:'استمتعت بـ %d يوماً من تجربة NectarOS\nفعّل ترخيصك للاستمرار وحفظ بياناتك',
  trial_data_warning:'⚠️ بياناتك في خطر',
  trial_data_warning_sub:'بياناتك محفوظة محلياً — لن تُحذف، لكن لن تتمكن من الوصول إليها بدون ترخيص',
  trial_enter_expired:'🔒 انتهت التجربة',
  trial_enter_trial:'🐝 دخول التطبيق (تجريبي)',

  /* Login */
  login_title:'تسجيل الدخول',
  login_user:'اسم المستخدم', login_pass:'كلمة المرور',
  login_btn:'🔓 دخول',

  /* Nav sections */
  nav_main:'الرئيسية',
  nav_bee_health:'صحة النحل',
  nav_equipment:'المعدات والمخزن',
  nav_commerce:'التجارة',
  nav_finance_rep:'التقارير المالية',
  nav_ai_section:'الذكاء الاصطناعي',
  nav_analytics:'التحليل والتخطيط',
  nav_monitoring:'المراقبة والميدان',
  nav_resources:'الموارد والمعرفة',
  nav_personal:'التنظيم الشخصي',
  nav_operations:'العمليات المتقدمة',
  nav_system:'النظام',

  /* Nav items */
  nav_dashboard:'لوحة التحكم',
  nav_apiaries:'المناحل والمواقع',
  nav_map:'الخريطة التفاعلية',
  nav_advanced:'مقاييس متقدمة',
  nav_hives:'الخلايا',
  nav_calendar:'التقويم',
  nav_inspections:'سجل الفحوصات',
  nav_treatments:'العلاجات',
  nav_weights:'سجل الأوزان',
  nav_harvest:'سجل الحصاد',
  nav_batches:'دفعات الإنتاج',
  nav_queens:'جينات الملكات',
  nav_health:'الشهادات الصحية',
  nav_assets:'باركود المعدات',
  nav_inventory:'المخزن',
  nav_store:'المتجر المباشر',
  nav_crm:'العملاء',
  nav_sales:'المبيعات',
  nav_expenses:'المصاريف',
  nav_profit:'الأرباح',
  nav_finance:'التقارير المالية',
  nav_settings:'الإعدادات',
  nav_ai:'الذكاء الاصطناعي',
  nav_aiplus:'AI+ متقدم',
  nav_contact:'اتصل بنا',
  nav_goals:'أهداف الإنتاج',
  nav_seasonal:'الجدول الموسمي',
  nav_radar:'مقارنة الخلايا',
  nav_compare:'مقارنة السنوات',
  nav_advstats:'إحصائيات متقدمة',
  nav_losses:'تحليل الخسائر',
  nav_annual:'التقرير السنوي',
  nav_weather:'طقس المناحل',
  nav_tempmon:'مراقبة الحرارة',
  nav_fieldmode:'وضع الحقل',
  nav_scanner:'ماسح الباركود',
  nav_foragemap:'خريطة الرعي',
  nav_plants:'نباتات المناحل',
  nav_disease:'دليل الأمراض',
  nav_calcs:'الحاسبات',
  nav_honeylabs:'مختبر العسل',
  nav_notifs:'التذكيرات',
  nav_pushnotifs:'إشعارات الهاتف',
  nav_tasks:'مهام الأسبوع',
  nav_journal:'المذكرة اليومية',
  nav_achievements:'الإنجازات',
  nav_orders:'الطلبات والشحن',
  nav_invoice:'الفواتير',
  nav_wareport:'تقرير واتساب',
  nav_team:'فريق العمل',
  nav_integrations:'التكاملات',
  nav_themes:'الثيمات والمظهر',
  nav_security:'الأمان والخصوصية',
  nav_logout:'تسجيل الخروج',

  /* Screen titles */
  scr_dashboard:'لوحة التحكم', scr_apiaries:'المناحل',
  scr_hives:'الخلايا', scr_calendar:'التقويم',
  scr_inspections:'سجل الفحوصات', scr_treatments:'العلاجات',
  scr_weights:'سجل الأوزان', scr_harvest:'سجل الحصاد',
  scr_queens:'جينات الملكات', scr_health:'الشهادات الصحية',
  scr_assets:'المعدات', scr_inventory:'المخزن',
  scr_store:'المتجر', scr_crm:'العملاء',
  scr_sales:'المبيعات', scr_expenses:'المصاريف',
  scr_profit:'الأرباح', scr_finance:'التقارير المالية',
  scr_settings:'الإعدادات', scr_ai:'الذكاء الاصطناعي',
  scr_contact:'اتصل بنا', scr_plants:'نباتات المناحل',
  scr_disease:'دليل الأمراض', scr_calcs:'الحاسبات',
  scr_weather:'طقس المناحل', scr_security:'الأمان',
  scr_themes:'الثيمات', scr_scanner:'ماسح الباركود',

  /* Common buttons */
  btn_add:'➕ إضافة', btn_save:'💾 حفظ', btn_cancel:'إلغاء',
  btn_delete:'🗑️ حذف', btn_edit:'✏️ تعديل', btn_close:'✕ إغلاق',
  btn_copy:'📋 نسخ', btn_share:'📤 مشاركة',
  btn_export:'📤 تصدير', btn_import:'📥 استيراد',
  btn_backup:'💾 نسخ احتياطي', btn_refresh:'🔄 تحديث',
  btn_search:'🔍 بحث', btn_filter:'🔽 فلتر',
  btn_send:'📤 إرسال', btn_print:'🖨️ طباعة',
  btn_confirm:'✅ تأكيد', btn_yes:'نعم', btn_no:'لا',
  btn_ok:'موافق', btn_back:'→ رجوع',
  btn_activate:'تفعيل', btn_deactivate:'تعطيل',
  btn_more:'المزيد',

  /* Common labels */
  lbl_name:'الاسم', lbl_date:'التاريخ',
  lbl_notes:'الملاحظات', lbl_status:'الحالة',
  lbl_type:'النوع', lbl_quantity:'الكمية',
  lbl_price:'السعر', lbl_total:'المجموع',
  lbl_weight:'الوزن', lbl_location:'الموقع',
  lbl_phone:'الهاتف', lbl_email:'البريد الإلكتروني',
  lbl_address:'العنوان', lbl_description:'الوصف',
  lbl_active:'نشط', lbl_inactive:'غير نشط',
  lbl_all:'الكل', lbl_none:'لا شيء',
  lbl_loading:'جاري التحميل...', lbl_no_data:'لا توجد بيانات',
  lbl_error:'خطأ', lbl_success:'تم بنجاح',
  lbl_warning:'تحذير',

  /* Contact page */
  contact_title:'📬 اتصل بنا', contact_sub:'نظام إدارة المناحل الذكي',
  contact_docs:'📄 وثائق التطبيق',
  contact_tech_card:'البطاقة التقنية', contact_tech_card_sub:'مواصفات وميزات التطبيق',
  contact_user_guide:'دليل المستخدم', contact_user_guide_sub:'شرح كامل لكل ميزات التطبيق',
  contact_support:'🛠️ الدعم الفني — تواصل معنا',
  contact_buy_title:'🛒 شراء ترخيص NectarOS',

  /* Bottom nav */
  bn_dashboard:'الرئيسية', bn_hives:'الخلايا',
  bn_apiaries:'المناحل', bn_ai:'الذكاء', bn_more:'المزيد',

  /* Language picker */
  lang_select:'اختر لغتك', lang_current:'اللغة الحالية',
},

/* ─────────────────────────────────────────────────────────────
   🇬🇧  ENGLISH
───────────────────────────────────────────────────────────── */
en: {
  _dir:'ltr', _name:'English', _flag:'🇬🇧',

  app_name:'NectarOS', app_sub:'Smart Apiary Management System',
  loading:'Loading',

  update_available:'🎉 New version available — tap to update',
  update_safe:'Your data is safely preserved',
  update_btn:'⬆️ Update',

  lic_title:'NectarOS', lic_sub:'License System',
  lic_tab_trial:'⏱️ Trial', lic_tab_activate:'🔑 Activate', lic_tab_devices:'📱 Devices',
  lic_extend_trial:'⏳ Extend trial by 15 days',
  lic_enter_app:'🐝 Enter App',
  lic_device_hint:'🔑 Your Device ID (send it to the developer to get your serial)',
  lic_copy_device:'📋 Copy Device ID',
  lic_serial_label:'Enter Activation Code (Serial)',
  lic_serial_placeholder:'XXXX-XXXX-XXXX-XXXX',
  lic_activate_btn:'✅ Activate License',
  lic_buy_title:'🛒 How to buy a license?',
  lic_buy_step1:'Copy your Device ID above',
  lic_buy_step2:'Send it with payment via one of the methods below',
  lic_buy_step3:'You will receive your activation code within 24 hours',
  lic_wa_btn:'💬 Contact us on WhatsApp',
  lic_wa_hint:'Send your Device ID and payment receipt to activate your license',

  trial_active:'Trial Active', trial_expired:'Expired',
  trial_days_left:'days left', trial_total_days:'total days',
  trial_extension:'Extension',
  trial_almost_up:'Time is running out!',
  trial_few_days:'Only a few days left',
  trial_mode:'Trial Mode',
  trial_elapsed:'elapsed',
  trial_of:'of',
  trial_activate_now:'⚡ Activate your license before time runs out',
  trial_data_safe:'Your data is safe and will transfer to the paid version automatically',
  trial_used:'Used', trial_available:'Available',
  trial_ended_title:'Trial Period Ended!',
  trial_ended_sub:'You enjoyed %d days of NectarOS trial\nActivate your license to continue and preserve your data',
  trial_data_warning:'⚠️ Your data is at risk',
  trial_data_warning_sub:'Your data is stored locally — it will not be deleted, but you cannot access it without a license',
  trial_enter_expired:'🔒 Trial Ended',
  trial_enter_trial:'🐝 Enter App (Trial)',

  login_title:'Sign In',
  login_user:'Username', login_pass:'Password',
  login_btn:'🔓 Sign In',

  nav_main:'Main',
  nav_bee_health:'Bee Health',
  nav_equipment:'Equipment & Storage',
  nav_commerce:'Commerce',
  nav_finance_rep:'Financial Reports',
  nav_ai_section:'Artificial Intelligence',
  nav_analytics:'Analysis & Planning',
  nav_monitoring:'Monitoring & Field',
  nav_resources:'Resources & Knowledge',
  nav_personal:'Personal Management',
  nav_operations:'Advanced Operations',
  nav_system:'System',

  nav_dashboard:'Dashboard',
  nav_apiaries:'Apiaries & Locations',
  nav_map:'Interactive Map',
  nav_advanced:'Advanced Metrics',
  nav_hives:'Hives',
  nav_calendar:'Calendar',
  nav_inspections:'Inspection Log',
  nav_treatments:'Treatments',
  nav_weights:'Weight Log',
  nav_harvest:'Harvest Log',
  nav_batches:'Production Batches',
  nav_queens:'Queen Genetics',
  nav_health:'Health Certificates',
  nav_assets:'Equipment Barcode',
  nav_inventory:'Inventory',
  nav_store:'Direct Store',
  nav_crm:'Customers',
  nav_sales:'Sales',
  nav_expenses:'Expenses',
  nav_profit:'Profit',
  nav_finance:'Financial Reports',
  nav_settings:'Settings',
  nav_ai:'Artificial Intelligence',
  nav_aiplus:'AI+ Advanced',
  nav_contact:'Contact Us',
  nav_goals:'Production Goals',
  nav_seasonal:'Seasonal Schedule',
  nav_radar:'Hive Comparison',
  nav_compare:'Year Comparison',
  nav_advstats:'Advanced Statistics',
  nav_losses:'Loss Analysis',
  nav_annual:'Annual Report',
  nav_weather:'Apiary Weather',
  nav_tempmon:'Temperature Monitor',
  nav_fieldmode:'Field Mode',
  nav_scanner:'Barcode Scanner',
  nav_foragemap:'Forage Map',
  nav_plants:'Apiary Plants',
  nav_disease:'Disease Guide',
  nav_calcs:'Calculators',
  nav_honeylabs:'Honey Lab',
  nav_notifs:'Reminders',
  nav_pushnotifs:'Phone Notifications',
  nav_tasks:'Weekly Tasks',
  nav_journal:'Daily Journal',
  nav_achievements:'Achievements',
  nav_orders:'Orders & Shipping',
  nav_invoice:'Invoices',
  nav_wareport:'WhatsApp Report',
  nav_team:'Work Team',
  nav_integrations:'Integrations',
  nav_themes:'Themes & Appearance',
  nav_security:'Security & Privacy',
  nav_logout:'Sign Out',

  scr_dashboard:'Dashboard', scr_apiaries:'Apiaries',
  scr_hives:'Hives', scr_calendar:'Calendar',
  scr_inspections:'Inspection Log', scr_treatments:'Treatments',
  scr_weights:'Weight Log', scr_harvest:'Harvest Log',
  scr_queens:'Queen Genetics', scr_health:'Health Certificates',
  scr_assets:'Equipment', scr_inventory:'Inventory',
  scr_store:'Store', scr_crm:'Customers',
  scr_sales:'Sales', scr_expenses:'Expenses',
  scr_profit:'Profit', scr_finance:'Financial Reports',
  scr_settings:'Settings', scr_ai:'Artificial Intelligence',
  scr_contact:'Contact Us', scr_plants:'Apiary Plants',
  scr_disease:'Disease Guide', scr_calcs:'Calculators',
  scr_weather:'Apiary Weather', scr_security:'Security',
  scr_themes:'Themes', scr_scanner:'Barcode Scanner',

  btn_add:'➕ Add', btn_save:'💾 Save', btn_cancel:'Cancel',
  btn_delete:'🗑️ Delete', btn_edit:'✏️ Edit', btn_close:'✕ Close',
  btn_copy:'📋 Copy', btn_share:'📤 Share',
  btn_export:'📤 Export', btn_import:'📥 Import',
  btn_backup:'💾 Backup', btn_refresh:'🔄 Refresh',
  btn_search:'🔍 Search', btn_filter:'🔽 Filter',
  btn_send:'📤 Send', btn_print:'🖨️ Print',
  btn_confirm:'✅ Confirm', btn_yes:'Yes', btn_no:'No',
  btn_ok:'OK', btn_back:'← Back',
  btn_activate:'Activate', btn_deactivate:'Deactivate',
  btn_more:'More',

  lbl_name:'Name', lbl_date:'Date',
  lbl_notes:'Notes', lbl_status:'Status',
  lbl_type:'Type', lbl_quantity:'Quantity',
  lbl_price:'Price', lbl_total:'Total',
  lbl_weight:'Weight', lbl_location:'Location',
  lbl_phone:'Phone', lbl_email:'Email',
  lbl_address:'Address', lbl_description:'Description',
  lbl_active:'Active', lbl_inactive:'Inactive',
  lbl_all:'All', lbl_none:'None',
  lbl_loading:'Loading...', lbl_no_data:'No data available',
  lbl_error:'Error', lbl_success:'Success',
  lbl_warning:'Warning',

  contact_title:'📬 Contact Us', contact_sub:'Smart Apiary Management System',
  contact_docs:'📄 App Documents',
  contact_tech_card:'Technical Sheet', contact_tech_card_sub:'App specifications and features',
  contact_user_guide:'User Guide', contact_user_guide_sub:'Complete guide to all app features',
  contact_support:'🛠️ Technical Support — Contact Us',
  contact_buy_title:'🛒 Purchase NectarOS License',

  bn_dashboard:'Home', bn_hives:'Hives',
  bn_apiaries:'Apiaries', bn_ai:'AI', bn_more:'More',

  lang_select:'Select your language', lang_current:'Current language',
},

/* ─────────────────────────────────────────────────────────────
   🇫🇷  FRANÇAIS
───────────────────────────────────────────────────────────── */
fr: {
  _dir:'ltr', _name:'Français', _flag:'🇫🇷',

  app_name:'NectarOS', app_sub:'Système Intelligent de Gestion du Rucher',
  loading:'Chargement',

  update_available:'🎉 Nouvelle version disponible — appuyez pour mettre à jour',
  update_safe:'Vos données sont préservées en sécurité',
  update_btn:'⬆️ Mettre à jour',

  lic_title:'NectarOS', lic_sub:'Système de Licence',
  lic_tab_trial:'⏱️ Essai', lic_tab_activate:'🔑 Activer', lic_tab_devices:'📱 Appareils',
  lic_extend_trial:'⏳ Prolonger l\'essai de 15 jours',
  lic_enter_app:'🐝 Entrer dans l\'App',
  lic_device_hint:'🔑 Votre ID d\'appareil (envoyez-le au développeur pour obtenir votre code)',
  lic_copy_device:'📋 Copier l\'ID d\'appareil',
  lic_serial_label:'Entrez le code d\'activation (Série)',
  lic_serial_placeholder:'XXXX-XXXX-XXXX-XXXX',
  lic_activate_btn:'✅ Activer la licence',
  lic_buy_title:'🛒 Comment acheter une licence?',
  lic_buy_step1:'Copiez votre ID d\'appareil ci-dessus',
  lic_buy_step2:'Envoyez-le avec le paiement via l\'une des méthodes ci-dessous',
  lic_buy_step3:'Vous recevrez votre code d\'activation dans 24 heures',
  lic_wa_btn:'💬 Contactez-nous sur WhatsApp',
  lic_wa_hint:'Envoyez votre ID et votre reçu de paiement pour activer votre licence',

  trial_active:'Essai Actif', trial_expired:'Expiré',
  trial_days_left:'jours restants', trial_total_days:'jours au total',
  trial_extension:'Prolongation',
  trial_almost_up:'Le temps est limité!',
  trial_few_days:'Quelques jours restants',
  trial_mode:'Mode Essai',
  trial_elapsed:'écoulés',
  trial_of:'sur',
  trial_activate_now:'⚡ Activez votre licence avant expiration',
  trial_data_safe:'Vos données sont sécurisées et seront transférées automatiquement',
  trial_used:'Utilisé', trial_available:'Disponible',
  trial_ended_title:'Période d\'essai terminée!',
  trial_ended_sub:'Vous avez profité de %d jours d\'essai NectarOS\nActivez votre licence pour continuer',
  trial_data_warning:'⚠️ Vos données sont en danger',
  trial_data_warning_sub:'Vos données sont stockées localement — elles ne seront pas supprimées, mais sans licence vous ne pourrez pas y accéder',
  trial_enter_expired:'🔒 Essai Terminé',
  trial_enter_trial:'🐝 Entrer (Essai)',

  login_title:'Connexion',
  login_user:'Nom d\'utilisateur', login_pass:'Mot de passe',
  login_btn:'🔓 Connexion',

  nav_main:'Principal', nav_bee_health:'Santé des Abeilles',
  nav_equipment:'Équipements & Stockage', nav_commerce:'Commerce',
  nav_finance_rep:'Rapports Financiers', nav_ai_section:'Intelligence Artificielle',
  nav_analytics:'Analyse & Planification', nav_monitoring:'Surveillance & Terrain',
  nav_resources:'Ressources & Savoir', nav_personal:'Organisation Personnelle',
  nav_operations:'Opérations Avancées', nav_system:'Système',

  nav_dashboard:'Tableau de Bord', nav_apiaries:'Ruchers & Emplacements',
  nav_map:'Carte Interactive', nav_advanced:'Métriques Avancées',
  nav_hives:'Ruches', nav_calendar:'Calendrier',
  nav_inspections:'Journal des Inspections', nav_treatments:'Traitements',
  nav_weights:'Journal des Poids', nav_harvest:'Journal des Récoltes',
  nav_batches:'Lots de Production', nav_queens:'Génétique des Reines',
  nav_health:'Certificats Sanitaires', nav_assets:'Codes-barres',
  nav_inventory:'Inventaire', nav_store:'Boutique',
  nav_crm:'Clients', nav_sales:'Ventes',
  nav_expenses:'Dépenses', nav_profit:'Bénéfices',
  nav_finance:'Rapports Financiers', nav_settings:'Paramètres',
  nav_ai:'Intelligence Artificielle', nav_aiplus:'IA+ Avancée',
  nav_contact:'Contactez-nous', nav_goals:'Objectifs de Production',
  nav_seasonal:'Planning Saisonnier', nav_radar:'Comparaison Ruches',
  nav_compare:'Comparaison Annuelle', nav_advstats:'Statistiques Avancées',
  nav_losses:'Analyse des Pertes', nav_annual:'Rapport Annuel',
  nav_weather:'Météo du Rucher', nav_tempmon:'Moniteur de Température',
  nav_fieldmode:'Mode Terrain', nav_scanner:'Scanner Code-barres',
  nav_foragemap:'Carte de Butinage', nav_plants:'Plantes du Rucher',
  nav_disease:'Guide des Maladies', nav_calcs:'Calculateurs',
  nav_honeylabs:'Laboratoire Miel', nav_notifs:'Rappels',
  nav_pushnotifs:'Notifications', nav_tasks:'Tâches Hebdomadaires',
  nav_journal:'Journal Quotidien', nav_achievements:'Réalisations',
  nav_orders:'Commandes & Livraison', nav_invoice:'Factures',
  nav_wareport:'Rapport WhatsApp', nav_team:'Équipe',
  nav_integrations:'Intégrations', nav_themes:'Thèmes & Apparence',
  nav_security:'Sécurité & Confidentialité', nav_logout:'Déconnexion',

  scr_dashboard:'Tableau de Bord', scr_apiaries:'Ruchers',
  scr_hives:'Ruches', scr_calendar:'Calendrier',
  scr_inspections:'Inspections', scr_treatments:'Traitements',
  scr_weights:'Poids', scr_harvest:'Récoltes',
  scr_queens:'Reines', scr_health:'Certificats',
  scr_assets:'Équipements', scr_inventory:'Inventaire',
  scr_store:'Boutique', scr_crm:'Clients',
  scr_sales:'Ventes', scr_expenses:'Dépenses',
  scr_profit:'Bénéfices', scr_finance:'Rapports',
  scr_settings:'Paramètres', scr_ai:'Intelligence Artificielle',
  scr_contact:'Contactez-nous', scr_plants:'Plantes',
  scr_disease:'Maladies', scr_calcs:'Calculateurs',
  scr_weather:'Météo', scr_security:'Sécurité',
  scr_themes:'Thèmes', scr_scanner:'Scanner',

  btn_add:'➕ Ajouter', btn_save:'💾 Enregistrer', btn_cancel:'Annuler',
  btn_delete:'🗑️ Supprimer', btn_edit:'✏️ Modifier', btn_close:'✕ Fermer',
  btn_copy:'📋 Copier', btn_share:'📤 Partager',
  btn_export:'📤 Exporter', btn_import:'📥 Importer',
  btn_backup:'💾 Sauvegarde', btn_refresh:'🔄 Actualiser',
  btn_search:'🔍 Rechercher', btn_filter:'🔽 Filtrer',
  btn_send:'📤 Envoyer', btn_print:'🖨️ Imprimer',
  btn_confirm:'✅ Confirmer', btn_yes:'Oui', btn_no:'Non',
  btn_ok:'OK', btn_back:'← Retour',
  btn_activate:'Activer', btn_deactivate:'Désactiver',
  btn_more:'Plus',

  lbl_name:'Nom', lbl_date:'Date',
  lbl_notes:'Notes', lbl_status:'Statut',
  lbl_type:'Type', lbl_quantity:'Quantité',
  lbl_price:'Prix', lbl_total:'Total',
  lbl_weight:'Poids', lbl_location:'Emplacement',
  lbl_phone:'Téléphone', lbl_email:'Email',
  lbl_address:'Adresse', lbl_description:'Description',
  lbl_active:'Actif', lbl_inactive:'Inactif',
  lbl_all:'Tout', lbl_none:'Aucun',
  lbl_loading:'Chargement...', lbl_no_data:'Aucune donnée disponible',
  lbl_error:'Erreur', lbl_success:'Succès',
  lbl_warning:'Avertissement',

  contact_title:'📬 Contactez-nous', contact_sub:'Système Intelligent de Gestion du Rucher',
  contact_docs:'📄 Documents de l\'App',
  contact_tech_card:'Fiche Technique', contact_tech_card_sub:'Spécifications et fonctionnalités',
  contact_user_guide:'Guide Utilisateur', contact_user_guide_sub:'Guide complet de toutes les fonctionnalités',
  contact_support:'🛠️ Support Technique — Contactez-nous',
  contact_buy_title:'🛒 Acheter une licence NectarOS',

  bn_dashboard:'Accueil', bn_hives:'Ruches',
  bn_apiaries:'Ruchers', bn_ai:'IA', bn_more:'Plus',

  lang_select:'Choisissez votre langue', lang_current:'Langue actuelle',
},

/* ─────────────────────────────────────────────────────────────
   🇹🇷  TÜRKÇE
───────────────────────────────────────────────────────────── */
tr: {
  _dir:'ltr', _name:'Türkçe', _flag:'🇹🇷',

  app_name:'NectarOS', app_sub:'Akıllı Arı Çiftliği Yönetim Sistemi',
  loading:'Yükleniyor',

  update_available:'🎉 Yeni sürüm mevcut — güncellemek için dokunun',
  update_safe:'Verileriniz güvenle korunmaktadır',
  update_btn:'⬆️ Güncelle',

  lic_title:'NectarOS', lic_sub:'Lisans Sistemi',
  lic_tab_trial:'⏱️ Deneme', lic_tab_activate:'🔑 Etkinleştir', lic_tab_devices:'📱 Cihazlar',
  lic_extend_trial:'⏳ Denemeyi 15 gün uzat',
  lic_enter_app:'🐝 Uygulamaya Gir',
  lic_device_hint:'🔑 Cihaz ID\'niz (seri almak için geliştiriye gönderin)',
  lic_copy_device:'📋 Cihaz ID\'yi Kopyala',
  lic_serial_label:'Etkinleştirme Kodunu Girin (Seri)',
  lic_serial_placeholder:'XXXX-XXXX-XXXX-XXXX',
  lic_activate_btn:'✅ Lisansı Etkinleştir',
  lic_buy_title:'🛒 Lisans nasıl satın alınır?',
  lic_buy_step1:'Yukarıdaki Cihaz ID\'nizi kopyalayın',
  lic_buy_step2:'Aşağıdaki yöntemlerden biriyle ödemeyle gönderin',
  lic_buy_step3:'24 saat içinde etkinleştirme kodunuzu alacaksınız',
  lic_wa_btn:'💬 WhatsApp\'tan bize ulaşın',
  lic_wa_hint:'Lisansınızı etkinleştirmek için Cihaz ID ve ödeme makbuzunuzu gönderin',

  trial_active:'Deneme Aktif', trial_expired:'Süresi Doldu',
  trial_days_left:'gün kaldı', trial_total_days:'toplam gün',
  trial_extension:'Uzatma',
  trial_almost_up:'Zaman tükeniyor!',
  trial_few_days:'Az gün kaldı',
  trial_mode:'Deneme Modu',
  trial_elapsed:'geçti',
  trial_of:'/',
  trial_activate_now:'⚡ Süresi dolmadan lisansınızı etkinleştirin',
  trial_data_safe:'Verileriniz güvende ve ücretli sürüme otomatik aktarılacak',
  trial_used:'Kullanıldı', trial_available:'Mevcut',
  trial_ended_title:'Deneme Süresi Sona Erdi!',
  trial_ended_sub:'NectarOS deneme süresinin %d gününden yararlandınız\nVerilerinizi korumak için lisansınızı etkinleştirin',
  trial_data_warning:'⚠️ Verileriniz tehlikede',
  trial_data_warning_sub:'Verileriniz yerel olarak depolanıyor — silinmeyecek, ancak lisans olmadan erişemezsiniz',
  trial_enter_expired:'🔒 Deneme Bitti',
  trial_enter_trial:'🐝 Uygulamaya Gir (Deneme)',

  login_title:'Giriş Yap',
  login_user:'Kullanıcı Adı', login_pass:'Şifre',
  login_btn:'🔓 Giriş',

  nav_main:'Ana', nav_bee_health:'Arı Sağlığı',
  nav_equipment:'Ekipman & Depo', nav_commerce:'Ticaret',
  nav_finance_rep:'Mali Raporlar', nav_ai_section:'Yapay Zeka',
  nav_analytics:'Analiz & Planlama', nav_monitoring:'İzleme & Saha',
  nav_resources:'Kaynaklar & Bilgi', nav_personal:'Kişisel Yönetim',
  nav_operations:'Gelişmiş İşlemler', nav_system:'Sistem',

  nav_dashboard:'Kontrol Paneli', nav_apiaries:'Arı Çiftlikleri',
  nav_map:'Etkileşimli Harita', nav_advanced:'Gelişmiş Metrikler',
  nav_hives:'Kovanlar', nav_calendar:'Takvim',
  nav_inspections:'İnceleme Kaydı', nav_treatments:'Tedaviler',
  nav_weights:'Ağırlık Kaydı', nav_harvest:'Hasat Kaydı',
  nav_batches:'Üretim Partileri', nav_queens:'Ana Arı Genetiği',
  nav_health:'Sağlık Sertifikaları', nav_assets:'Barkod',
  nav_inventory:'Envanter', nav_store:'Mağaza',
  nav_crm:'Müşteriler', nav_sales:'Satışlar',
  nav_expenses:'Giderler', nav_profit:'Kâr',
  nav_finance:'Mali Raporlar', nav_settings:'Ayarlar',
  nav_ai:'Yapay Zeka', nav_aiplus:'YZ+ Gelişmiş',
  nav_contact:'İletişim', nav_goals:'Üretim Hedefleri',
  nav_seasonal:'Mevsimsel Program', nav_radar:'Kovan Karşılaştırma',
  nav_compare:'Yıl Karşılaştırma', nav_advstats:'Gelişmiş İstatistikler',
  nav_losses:'Kayıp Analizi', nav_annual:'Yıllık Rapor',
  nav_weather:'Çiftlik Havası', nav_tempmon:'Sıcaklık Monitörü',
  nav_fieldmode:'Saha Modu', nav_scanner:'Barkod Tarayıcı',
  nav_foragemap:'Otlatma Haritası', nav_plants:'Arı Bitkileri',
  nav_disease:'Hastalık Rehberi', nav_calcs:'Hesaplayıcılar',
  nav_honeylabs:'Bal Laboratuvarı', nav_notifs:'Hatırlatıcılar',
  nav_pushnotifs:'Telefon Bildirimleri', nav_tasks:'Haftalık Görevler',
  nav_journal:'Günlük Defter', nav_achievements:'Başarılar',
  nav_orders:'Siparişler & Teslimat', nav_invoice:'Faturalar',
  nav_wareport:'WhatsApp Raporu', nav_team:'Çalışma Ekibi',
  nav_integrations:'Entegrasyonlar', nav_themes:'Temalar & Görünüm',
  nav_security:'Güvenlik & Gizlilik', nav_logout:'Çıkış Yap',

  scr_dashboard:'Kontrol Paneli', scr_apiaries:'Arı Çiftlikleri',
  scr_hives:'Kovanlar', scr_calendar:'Takvim',
  scr_inspections:'İnceleme Kaydı', scr_treatments:'Tedaviler',
  scr_weights:'Ağırlık Kaydı', scr_harvest:'Hasat Kaydı',
  scr_queens:'Ana Arı Genetiği', scr_health:'Sağlık Sertifikaları',
  scr_assets:'Ekipman', scr_inventory:'Envanter',
  scr_store:'Mağaza', scr_crm:'Müşteriler',
  scr_sales:'Satışlar', scr_expenses:'Giderler',
  scr_profit:'Kâr', scr_finance:'Mali Raporlar',
  scr_settings:'Ayarlar', scr_ai:'Yapay Zeka',
  scr_contact:'İletişim', scr_plants:'Arı Bitkileri',
  scr_disease:'Hastalık Rehberi', scr_calcs:'Hesaplayıcılar',
  scr_weather:'Çiftlik Havası', scr_security:'Güvenlik',
  scr_themes:'Temalar', scr_scanner:'Barkod Tarayıcı',

  btn_add:'➕ Ekle', btn_save:'💾 Kaydet', btn_cancel:'İptal',
  btn_delete:'🗑️ Sil', btn_edit:'✏️ Düzenle', btn_close:'✕ Kapat',
  btn_copy:'📋 Kopyala', btn_share:'📤 Paylaş',
  btn_export:'📤 Dışa Aktar', btn_import:'📥 İçe Aktar',
  btn_backup:'💾 Yedekle', btn_refresh:'🔄 Yenile',
  btn_search:'🔍 Ara', btn_filter:'🔽 Filtrele',
  btn_send:'📤 Gönder', btn_print:'🖨️ Yazdır',
  btn_confirm:'✅ Onayla', btn_yes:'Evet', btn_no:'Hayır',
  btn_ok:'Tamam', btn_back:'← Geri',
  btn_activate:'Etkinleştir', btn_deactivate:'Devre Dışı',
  btn_more:'Daha Fazla',

  lbl_name:'Ad', lbl_date:'Tarih',
  lbl_notes:'Notlar', lbl_status:'Durum',
  lbl_type:'Tür', lbl_quantity:'Miktar',
  lbl_price:'Fiyat', lbl_total:'Toplam',
  lbl_weight:'Ağırlık', lbl_location:'Konum',
  lbl_phone:'Telefon', lbl_email:'E-posta',
  lbl_address:'Adres', lbl_description:'Açıklama',
  lbl_active:'Aktif', lbl_inactive:'Pasif',
  lbl_all:'Tümü', lbl_none:'Hiçbiri',
  lbl_loading:'Yükleniyor...', lbl_no_data:'Veri mevcut değil',
  lbl_error:'Hata', lbl_success:'Başarılı',
  lbl_warning:'Uyarı',

  contact_title:'📬 İletişim', contact_sub:'Akıllı Arı Çiftliği Yönetim Sistemi',
  contact_docs:'📄 Uygulama Belgeleri',
  contact_tech_card:'Teknik Belge', contact_tech_card_sub:'Uygulama özellikleri',
  contact_user_guide:'Kullanıcı Kılavuzu', contact_user_guide_sub:'Tüm özellikler için tam kılavuz',
  contact_support:'🛠️ Teknik Destek — Bize Ulaşın',
  contact_buy_title:'🛒 NectarOS Lisansı Satın Al',

  bn_dashboard:'Ana Sayfa', bn_hives:'Kovanlar',
  bn_apiaries:'Çiftlikler', bn_ai:'YZ', bn_more:'Daha',

  lang_select:'Dilinizi seçin', lang_current:'Mevcut dil',
},

/* ─────────────────────────────────────────────────────────────
   🇪🇸  ESPAÑOL
───────────────────────────────────────────────────────────── */
es: {
  _dir:'ltr', _name:'Español', _flag:'🇪🇸',

  app_name:'NectarOS', app_sub:'Sistema Inteligente de Gestión de Colmenas',
  loading:'Cargando',

  update_available:'🎉 Nueva versión disponible — toca para actualizar',
  update_safe:'Tus datos están preservados de forma segura',
  update_btn:'⬆️ Actualizar',

  lic_title:'NectarOS', lic_sub:'Sistema de Licencia',
  lic_tab_trial:'⏱️ Prueba', lic_tab_activate:'🔑 Activar', lic_tab_devices:'📱 Dispositivos',
  lic_extend_trial:'⏳ Extender prueba 15 días',
  lic_enter_app:'🐝 Entrar a la App',
  lic_device_hint:'🔑 Tu ID de dispositivo (envíalo al desarrollador para obtener tu código)',
  lic_copy_device:'📋 Copiar ID de dispositivo',
  lic_serial_label:'Ingresa el código de activación (Serie)',
  lic_serial_placeholder:'XXXX-XXXX-XXXX-XXXX',
  lic_activate_btn:'✅ Activar Licencia',
  lic_buy_title:'🛒 ¿Cómo comprar una licencia?',
  lic_buy_step1:'Copia tu ID de dispositivo de arriba',
  lic_buy_step2:'Envíalo con el pago mediante uno de los métodos siguientes',
  lic_buy_step3:'Recibirás tu código de activación en 24 horas',
  lic_wa_btn:'💬 Contáctanos en WhatsApp',
  lic_wa_hint:'Envía tu ID de dispositivo y recibo de pago para activar tu licencia',

  trial_active:'Prueba Activa', trial_expired:'Expirado',
  trial_days_left:'días restantes', trial_total_days:'días totales',
  trial_extension:'Extensión',
  trial_almost_up:'¡El tiempo se agota!',
  trial_few_days:'Pocos días restantes',
  trial_mode:'Modo Prueba',
  trial_elapsed:'transcurridos',
  trial_of:'de',
  trial_activate_now:'⚡ Activa tu licencia antes de que expire',
  trial_data_safe:'Tus datos están seguros y se transferirán automáticamente',
  trial_used:'Usado', trial_available:'Disponible',
  trial_ended_title:'¡Período de prueba terminado!',
  trial_ended_sub:'Disfrutaste %d días de prueba de NectarOS\nActiva tu licencia para continuar',
  trial_data_warning:'⚠️ Tus datos están en riesgo',
  trial_data_warning_sub:'Tus datos están almacenados localmente — no se eliminarán, pero necesitas licencia para acceder',
  trial_enter_expired:'🔒 Prueba Terminada',
  trial_enter_trial:'🐝 Entrar a la App (Prueba)',

  login_title:'Iniciar Sesión',
  login_user:'Usuario', login_pass:'Contraseña',
  login_btn:'🔓 Iniciar Sesión',

  nav_main:'Principal', nav_bee_health:'Salud de las Abejas',
  nav_equipment:'Equipo & Almacén', nav_commerce:'Comercio',
  nav_finance_rep:'Informes Financieros', nav_ai_section:'Inteligencia Artificial',
  nav_analytics:'Análisis & Planificación', nav_monitoring:'Monitoreo & Campo',
  nav_resources:'Recursos & Conocimiento', nav_personal:'Gestión Personal',
  nav_operations:'Operaciones Avanzadas', nav_system:'Sistema',

  nav_dashboard:'Panel de Control', nav_apiaries:'Apiarios',
  nav_map:'Mapa Interactivo', nav_advanced:'Métricas Avanzadas',
  nav_hives:'Colmenas', nav_calendar:'Calendario',
  nav_inspections:'Registro de Inspecciones', nav_treatments:'Tratamientos',
  nav_weights:'Registro de Pesos', nav_harvest:'Registro de Cosecha',
  nav_batches:'Lotes de Producción', nav_queens:'Genética de Reinas',
  nav_health:'Certificados Sanitarios', nav_assets:'Códigos de Barras',
  nav_inventory:'Inventario', nav_store:'Tienda',
  nav_crm:'Clientes', nav_sales:'Ventas',
  nav_expenses:'Gastos', nav_profit:'Ganancias',
  nav_finance:'Informes Financieros', nav_settings:'Configuración',
  nav_ai:'Inteligencia Artificial', nav_aiplus:'IA+ Avanzada',
  nav_contact:'Contáctanos', nav_goals:'Metas de Producción',
  nav_seasonal:'Programa Estacional', nav_radar:'Comparación de Colmenas',
  nav_compare:'Comparación Anual', nav_advstats:'Estadísticas Avanzadas',
  nav_losses:'Análisis de Pérdidas', nav_annual:'Informe Anual',
  nav_weather:'Clima del Apiario', nav_tempmon:'Monitor de Temperatura',
  nav_fieldmode:'Modo Campo', nav_scanner:'Escáner de Código de Barras',
  nav_foragemap:'Mapa de Forrajeo', nav_plants:'Plantas del Apiario',
  nav_disease:'Guía de Enfermedades', nav_calcs:'Calculadoras',
  nav_honeylabs:'Laboratorio de Miel', nav_notifs:'Recordatorios',
  nav_pushnotifs:'Notificaciones', nav_tasks:'Tareas Semanales',
  nav_journal:'Diario', nav_achievements:'Logros',
  nav_orders:'Pedidos & Envíos', nav_invoice:'Facturas',
  nav_wareport:'Informe WhatsApp', nav_team:'Equipo de Trabajo',
  nav_integrations:'Integraciones', nav_themes:'Temas & Apariencia',
  nav_security:'Seguridad & Privacidad', nav_logout:'Cerrar Sesión',

  scr_dashboard:'Panel de Control', scr_apiaries:'Apiarios',
  scr_hives:'Colmenas', scr_calendar:'Calendario',
  scr_inspections:'Inspecciones', scr_treatments:'Tratamientos',
  scr_weights:'Pesos', scr_harvest:'Cosecha',
  scr_queens:'Reinas', scr_health:'Certificados',
  scr_assets:'Equipos', scr_inventory:'Inventario',
  scr_store:'Tienda', scr_crm:'Clientes',
  scr_sales:'Ventas', scr_expenses:'Gastos',
  scr_profit:'Ganancias', scr_finance:'Informes',
  scr_settings:'Configuración', scr_ai:'Inteligencia Artificial',
  scr_contact:'Contáctanos', scr_plants:'Plantas',
  scr_disease:'Enfermedades', scr_calcs:'Calculadoras',
  scr_weather:'Clima', scr_security:'Seguridad',
  scr_themes:'Temas', scr_scanner:'Escáner',

  btn_add:'➕ Agregar', btn_save:'💾 Guardar', btn_cancel:'Cancelar',
  btn_delete:'🗑️ Eliminar', btn_edit:'✏️ Editar', btn_close:'✕ Cerrar',
  btn_copy:'📋 Copiar', btn_share:'📤 Compartir',
  btn_export:'📤 Exportar', btn_import:'📥 Importar',
  btn_backup:'💾 Respaldo', btn_refresh:'🔄 Actualizar',
  btn_search:'🔍 Buscar', btn_filter:'🔽 Filtrar',
  btn_send:'📤 Enviar', btn_print:'🖨️ Imprimir',
  btn_confirm:'✅ Confirmar', btn_yes:'Sí', btn_no:'No',
  btn_ok:'OK', btn_back:'← Volver',
  btn_activate:'Activar', btn_deactivate:'Desactivar',
  btn_more:'Más',

  lbl_name:'Nombre', lbl_date:'Fecha',
  lbl_notes:'Notas', lbl_status:'Estado',
  lbl_type:'Tipo', lbl_quantity:'Cantidad',
  lbl_price:'Precio', lbl_total:'Total',
  lbl_weight:'Peso', lbl_location:'Ubicación',
  lbl_phone:'Teléfono', lbl_email:'Correo',
  lbl_address:'Dirección', lbl_description:'Descripción',
  lbl_active:'Activo', lbl_inactive:'Inactivo',
  lbl_all:'Todo', lbl_none:'Ninguno',
  lbl_loading:'Cargando...', lbl_no_data:'No hay datos disponibles',
  lbl_error:'Error', lbl_success:'Éxito',
  lbl_warning:'Advertencia',

  contact_title:'📬 Contáctanos', contact_sub:'Sistema Inteligente de Gestión de Colmenas',
  contact_docs:'📄 Documentos de la App',
  contact_tech_card:'Ficha Técnica', contact_tech_card_sub:'Especificaciones y características',
  contact_user_guide:'Guía de Usuario', contact_user_guide_sub:'Guía completa de todas las funciones',
  contact_support:'🛠️ Soporte Técnico — Contáctanos',
  contact_buy_title:'🛒 Comprar Licencia NectarOS',

  bn_dashboard:'Inicio', bn_hives:'Colmenas',
  bn_apiaries:'Apiarios', bn_ai:'IA', bn_more:'Más',

  lang_select:'Selecciona tu idioma', lang_current:'Idioma actual',
},

/* ─────────────────────────────────────────────────────────────
   🇩🇪  DEUTSCH
───────────────────────────────────────────────────────────── */
de: {
  _dir:'ltr', _name:'Deutsch', _flag:'🇩🇪',

  app_name:'NectarOS', app_sub:'Intelligentes Bienenstockmanagement-System',
  loading:'Laden',

  update_available:'🎉 Neue Version verfügbar — zum Aktualisieren tippen',
  update_safe:'Ihre Daten sind sicher gespeichert',
  update_btn:'⬆️ Aktualisieren',

  lic_title:'NectarOS', lic_sub:'Lizenzsystem',
  lic_tab_trial:'⏱️ Testversion', lic_tab_activate:'🔑 Aktivieren', lic_tab_devices:'📱 Geräte',
  lic_extend_trial:'⏳ Testversion um 15 Tage verlängern',
  lic_enter_app:'🐝 App betreten',
  lic_device_hint:'🔑 Ihre Geräte-ID (senden Sie sie an den Entwickler für Ihren Code)',
  lic_copy_device:'📋 Geräte-ID kopieren',
  lic_serial_label:'Aktivierungscode eingeben (Seriennummer)',
  lic_serial_placeholder:'XXXX-XXXX-XXXX-XXXX',
  lic_activate_btn:'✅ Lizenz aktivieren',
  lic_buy_title:'🛒 Wie kaufe ich eine Lizenz?',
  lic_buy_step1:'Kopieren Sie Ihre Geräte-ID oben',
  lic_buy_step2:'Senden Sie sie mit der Zahlung über eine der folgenden Methoden',
  lic_buy_step3:'Sie erhalten Ihren Aktivierungscode innerhalb von 24 Stunden',
  lic_wa_btn:'💬 Kontaktieren Sie uns auf WhatsApp',
  lic_wa_hint:'Senden Sie Ihre Geräte-ID und Zahlungsnachweis, um Ihre Lizenz zu aktivieren',

  trial_active:'Testversion Aktiv', trial_expired:'Abgelaufen',
  trial_days_left:'Tage verbleibend', trial_total_days:'Gesamttage',
  trial_extension:'Verlängerung',
  trial_almost_up:'Die Zeit läuft ab!',
  trial_few_days:'Nur noch wenige Tage',
  trial_mode:'Testmodus',
  trial_elapsed:'vergangen',
  trial_of:'von',
  trial_activate_now:'⚡ Aktivieren Sie Ihre Lizenz vor Ablauf',
  trial_data_safe:'Ihre Daten sind sicher und werden automatisch übertragen',
  trial_used:'Verwendet', trial_available:'Verfügbar',
  trial_ended_title:'Testzeitraum beendet!',
  trial_ended_sub:'Sie haben %d Tage NectarOS-Test genossen\nAktivieren Sie Ihre Lizenz, um fortzufahren',
  trial_data_warning:'⚠️ Ihre Daten sind gefährdet',
  trial_data_warning_sub:'Ihre Daten werden lokal gespeichert — sie werden nicht gelöscht, aber ohne Lizenz ist kein Zugriff möglich',
  trial_enter_expired:'🔒 Test Beendet',
  trial_enter_trial:'🐝 App betreten (Test)',

  login_title:'Anmelden',
  login_user:'Benutzername', login_pass:'Passwort',
  login_btn:'🔓 Anmelden',

  nav_main:'Haupt', nav_bee_health:'Bienengesundheit',
  nav_equipment:'Ausrüstung & Lager', nav_commerce:'Handel',
  nav_finance_rep:'Finanzberichte', nav_ai_section:'Künstliche Intelligenz',
  nav_analytics:'Analyse & Planung', nav_monitoring:'Überwachung & Feld',
  nav_resources:'Ressourcen & Wissen', nav_personal:'Persönliche Verwaltung',
  nav_operations:'Erweiterte Operationen', nav_system:'System',

  nav_dashboard:'Dashboard', nav_apiaries:'Bienenstöcke & Standorte',
  nav_map:'Interaktive Karte', nav_advanced:'Erweiterte Metriken',
  nav_hives:'Bienenstöcke', nav_calendar:'Kalender',
  nav_inspections:'Inspektionsprotokoll', nav_treatments:'Behandlungen',
  nav_weights:'Gewichtsprotokoll', nav_harvest:'Ernte',
  nav_batches:'Produktionschargen', nav_queens:'Königin-Genetik',
  nav_health:'Gesundheitszertifikate', nav_assets:'Barcodes',
  nav_inventory:'Inventar', nav_store:'Shop',
  nav_crm:'Kunden', nav_sales:'Verkäufe',
  nav_expenses:'Ausgaben', nav_profit:'Gewinn',
  nav_finance:'Finanzberichte', nav_settings:'Einstellungen',
  nav_ai:'Künstliche Intelligenz', nav_aiplus:'KI+ Erweitert',
  nav_contact:'Kontakt', nav_goals:'Produktionsziele',
  nav_seasonal:'Saisonplan', nav_radar:'Bienenstock-Vergleich',
  nav_compare:'Jahresvergleich', nav_advstats:'Erweiterte Statistiken',
  nav_losses:'Verlustanalyse', nav_annual:'Jahresbericht',
  nav_weather:'Bienenstockwetter', nav_tempmon:'Temperaturmonitor',
  nav_fieldmode:'Feldmodus', nav_scanner:'Barcode-Scanner',
  nav_foragemap:'Weide-Karte', nav_plants:'Bienenpflanzen',
  nav_disease:'Krankheitsleitfaden', nav_calcs:'Rechner',
  nav_honeylabs:'Honiglabor', nav_notifs:'Erinnerungen',
  nav_pushnotifs:'Benachrichtigungen', nav_tasks:'Wöchentliche Aufgaben',
  nav_journal:'Tagestagebuch', nav_achievements:'Errungenschaften',
  nav_orders:'Bestellungen & Versand', nav_invoice:'Rechnungen',
  nav_wareport:'WhatsApp-Bericht', nav_team:'Arbeitsteam',
  nav_integrations:'Integrationen', nav_themes:'Themen & Aussehen',
  nav_security:'Sicherheit & Datenschutz', nav_logout:'Abmelden',

  scr_dashboard:'Dashboard', scr_apiaries:'Bienenstöcke',
  scr_hives:'Bienenstöcke', scr_calendar:'Kalender',
  scr_inspections:'Inspektionen', scr_treatments:'Behandlungen',
  scr_weights:'Gewichte', scr_harvest:'Ernte',
  scr_queens:'Königinnen', scr_health:'Zertifikate',
  scr_assets:'Ausrüstung', scr_inventory:'Inventar',
  scr_store:'Shop', scr_crm:'Kunden',
  scr_sales:'Verkäufe', scr_expenses:'Ausgaben',
  scr_profit:'Gewinn', scr_finance:'Berichte',
  scr_settings:'Einstellungen', scr_ai:'Künstliche Intelligenz',
  scr_contact:'Kontakt', scr_plants:'Pflanzen',
  scr_disease:'Krankheiten', scr_calcs:'Rechner',
  scr_weather:'Wetter', scr_security:'Sicherheit',
  scr_themes:'Themen', scr_scanner:'Barcode-Scanner',

  btn_add:'➕ Hinzufügen', btn_save:'💾 Speichern', btn_cancel:'Abbrechen',
  btn_delete:'🗑️ Löschen', btn_edit:'✏️ Bearbeiten', btn_close:'✕ Schließen',
  btn_copy:'📋 Kopieren', btn_share:'📤 Teilen',
  btn_export:'📤 Exportieren', btn_import:'📥 Importieren',
  btn_backup:'💾 Sicherung', btn_refresh:'🔄 Aktualisieren',
  btn_search:'🔍 Suchen', btn_filter:'🔽 Filtern',
  btn_send:'📤 Senden', btn_print:'🖨️ Drucken',
  btn_confirm:'✅ Bestätigen', btn_yes:'Ja', btn_no:'Nein',
  btn_ok:'OK', btn_back:'← Zurück',
  btn_activate:'Aktivieren', btn_deactivate:'Deaktivieren',
  btn_more:'Mehr',

  lbl_name:'Name', lbl_date:'Datum',
  lbl_notes:'Notizen', lbl_status:'Status',
  lbl_type:'Typ', lbl_quantity:'Menge',
  lbl_price:'Preis', lbl_total:'Gesamt',
  lbl_weight:'Gewicht', lbl_location:'Standort',
  lbl_phone:'Telefon', lbl_email:'E-Mail',
  lbl_address:'Adresse', lbl_description:'Beschreibung',
  lbl_active:'Aktiv', lbl_inactive:'Inaktiv',
  lbl_all:'Alle', lbl_none:'Keine',
  lbl_loading:'Laden...', lbl_no_data:'Keine Daten verfügbar',
  lbl_error:'Fehler', lbl_success:'Erfolg',
  lbl_warning:'Warnung',

  contact_title:'📬 Kontakt', contact_sub:'Intelligentes Bienenstockmanagement-System',
  contact_docs:'📄 App-Dokumente',
  contact_tech_card:'Technisches Datenblatt', contact_tech_card_sub:'App-Spezifikationen',
  contact_user_guide:'Benutzerhandbuch', contact_user_guide_sub:'Vollständige Anleitung',
  contact_support:'🛠️ Technischer Support — Kontaktieren Sie uns',
  contact_buy_title:'🛒 NectarOS-Lizenz kaufen',

  bn_dashboard:'Startseite', bn_hives:'Bienenstöcke',
  bn_apiaries:'Bienenstöcke', bn_ai:'KI', bn_more:'Mehr',

  lang_select:'Wählen Sie Ihre Sprache', lang_current:'Aktuelle Sprache',
},

/* ─────────────────────────────────────────────────────────────
   🇮🇹  ITALIANO
───────────────────────────────────────────────────────────── */
it: {
  _dir:'ltr', _name:'Italiano', _flag:'🇮🇹',

  app_name:'NectarOS', app_sub:'Sistema Intelligente di Gestione degli Apiari',
  loading:'Caricamento',

  update_available:'🎉 Nuova versione disponibile — tocca per aggiornare',
  update_safe:'I tuoi dati sono conservati in modo sicuro',
  update_btn:'⬆️ Aggiorna',

  lic_title:'NectarOS', lic_sub:'Sistema di Licenza',
  lic_tab_trial:'⏱️ Prova', lic_tab_activate:'🔑 Attiva', lic_tab_devices:'📱 Dispositivi',
  lic_extend_trial:'⏳ Estendi prova di 15 giorni',
  lic_enter_app:'🐝 Entra nell\'App',
  lic_device_hint:'🔑 Il tuo ID dispositivo (invialo allo sviluppatore per il codice)',
  lic_copy_device:'📋 Copia ID dispositivo',
  lic_serial_label:'Inserisci il codice di attivazione (Seriale)',
  lic_serial_placeholder:'XXXX-XXXX-XXXX-XXXX',
  lic_activate_btn:'✅ Attiva Licenza',
  lic_buy_title:'🛒 Come acquistare una licenza?',
  lic_buy_step1:'Copia il tuo ID dispositivo sopra',
  lic_buy_step2:'Invialo con il pagamento tramite uno dei metodi seguenti',
  lic_buy_step3:'Riceverai il tuo codice di attivazione entro 24 ore',
  lic_wa_btn:'💬 Contattaci su WhatsApp',
  lic_wa_hint:'Invia il tuo ID dispositivo e la ricevuta di pagamento per attivare la licenza',

  trial_active:'Prova Attiva', trial_expired:'Scaduto',
  trial_days_left:'giorni rimanenti', trial_total_days:'giorni totali',
  trial_extension:'Estensione',
  trial_almost_up:'Il tempo sta per scadere!',
  trial_few_days:'Solo pochi giorni rimanenti',
  trial_mode:'Modalità Prova',
  trial_elapsed:'trascorsi',
  trial_of:'di',
  trial_activate_now:'⚡ Attiva la tua licenza prima della scadenza',
  trial_data_safe:'I tuoi dati sono al sicuro e verranno trasferiti automaticamente',
  trial_used:'Usato', trial_available:'Disponibile',
  trial_ended_title:'Periodo di prova terminato!',
  trial_ended_sub:'Hai goduto di %d giorni di prova NectarOS\nAttiva la tua licenza per continuare',
  trial_data_warning:'⚠️ I tuoi dati sono a rischio',
  trial_data_warning_sub:'I tuoi dati sono memorizzati localmente — non verranno eliminati, ma senza licenza non puoi accedervi',
  trial_enter_expired:'🔒 Prova Terminata',
  trial_enter_trial:'🐝 Entra nell\'App (Prova)',

  login_title:'Accedi',
  login_user:'Nome utente', login_pass:'Password',
  login_btn:'🔓 Accedi',

  nav_main:'Principale', nav_bee_health:'Salute delle Api',
  nav_equipment:'Attrezzature & Magazzino', nav_commerce:'Commercio',
  nav_finance_rep:'Rapporti Finanziari', nav_ai_section:'Intelligenza Artificiale',
  nav_analytics:'Analisi & Pianificazione', nav_monitoring:'Monitoraggio & Campo',
  nav_resources:'Risorse & Conoscenza', nav_personal:'Gestione Personale',
  nav_operations:'Operazioni Avanzate', nav_system:'Sistema',

  nav_dashboard:'Pannello di Controllo', nav_apiaries:'Apiari',
  nav_map:'Mappa Interattiva', nav_advanced:'Metriche Avanzate',
  nav_hives:'Arnie', nav_calendar:'Calendario',
  nav_inspections:'Registro Ispezioni', nav_treatments:'Trattamenti',
  nav_weights:'Registro Pesi', nav_harvest:'Registro Raccolta',
  nav_batches:'Lotti di Produzione', nav_queens:'Genetica delle Regine',
  nav_health:'Certificati Sanitari', nav_assets:'Codici a Barre',
  nav_inventory:'Inventario', nav_store:'Negozio',
  nav_crm:'Clienti', nav_sales:'Vendite',
  nav_expenses:'Spese', nav_profit:'Profitti',
  nav_finance:'Rapporti Finanziari', nav_settings:'Impostazioni',
  nav_ai:'Intelligenza Artificiale', nav_aiplus:'IA+ Avanzata',
  nav_contact:'Contattaci', nav_goals:'Obiettivi di Produzione',
  nav_seasonal:'Programma Stagionale', nav_radar:'Confronto Arnie',
  nav_compare:'Confronto Annuale', nav_advstats:'Statistiche Avanzate',
  nav_losses:'Analisi Perdite', nav_annual:'Rapporto Annuale',
  nav_weather:'Meteo Apiario', nav_tempmon:'Monitor Temperatura',
  nav_fieldmode:'Modalità Campo', nav_scanner:'Scanner Codici a Barre',
  nav_foragemap:'Mappa Pascolo', nav_plants:'Piante dell\'Apiario',
  nav_disease:'Guida alle Malattie', nav_calcs:'Calcolatori',
  nav_honeylabs:'Laboratorio Miele', nav_notifs:'Promemoria',
  nav_pushnotifs:'Notifiche Telefono', nav_tasks:'Compiti Settimanali',
  nav_journal:'Diario Quotidiano', nav_achievements:'Risultati',
  nav_orders:'Ordini & Spedizioni', nav_invoice:'Fatture',
  nav_wareport:'Report WhatsApp', nav_team:'Team di Lavoro',
  nav_integrations:'Integrazioni', nav_themes:'Temi & Aspetto',
  nav_security:'Sicurezza & Privacy', nav_logout:'Disconnetti',

  scr_dashboard:'Pannello', scr_apiaries:'Apiari',
  scr_hives:'Arnie', scr_calendar:'Calendario',
  scr_inspections:'Ispezioni', scr_treatments:'Trattamenti',
  scr_weights:'Pesi', scr_harvest:'Raccolta',
  scr_queens:'Regine', scr_health:'Certificati',
  scr_assets:'Attrezzature', scr_inventory:'Inventario',
  scr_store:'Negozio', scr_crm:'Clienti',
  scr_sales:'Vendite', scr_expenses:'Spese',
  scr_profit:'Profitti', scr_finance:'Rapporti',
  scr_settings:'Impostazioni', scr_ai:'Intelligenza Artificiale',
  scr_contact:'Contattaci', scr_plants:'Piante',
  scr_disease:'Malattie', scr_calcs:'Calcolatori',
  scr_weather:'Meteo', scr_security:'Sicurezza',
  scr_themes:'Temi', scr_scanner:'Scanner',

  btn_add:'➕ Aggiungi', btn_save:'💾 Salva', btn_cancel:'Annulla',
  btn_delete:'🗑️ Elimina', btn_edit:'✏️ Modifica', btn_close:'✕ Chiudi',
  btn_copy:'📋 Copia', btn_share:'📤 Condividi',
  btn_export:'📤 Esporta', btn_import:'📥 Importa',
  btn_backup:'💾 Backup', btn_refresh:'🔄 Aggiorna',
  btn_search:'🔍 Cerca', btn_filter:'🔽 Filtra',
  btn_send:'📤 Invia', btn_print:'🖨️ Stampa',
  btn_confirm:'✅ Conferma', btn_yes:'Sì', btn_no:'No',
  btn_ok:'OK', btn_back:'← Indietro',
  btn_activate:'Attiva', btn_deactivate:'Disattiva',
  btn_more:'Altro',

  lbl_name:'Nome', lbl_date:'Data',
  lbl_notes:'Note', lbl_status:'Stato',
  lbl_type:'Tipo', lbl_quantity:'Quantità',
  lbl_price:'Prezzo', lbl_total:'Totale',
  lbl_weight:'Peso', lbl_location:'Posizione',
  lbl_phone:'Telefono', lbl_email:'Email',
  lbl_address:'Indirizzo', lbl_description:'Descrizione',
  lbl_active:'Attivo', lbl_inactive:'Inattivo',
  lbl_all:'Tutto', lbl_none:'Nessuno',
  lbl_loading:'Caricamento...', lbl_no_data:'Nessun dato disponibile',
  lbl_error:'Errore', lbl_success:'Successo',
  lbl_warning:'Avviso',

  contact_title:'📬 Contattaci', contact_sub:'Sistema Intelligente di Gestione degli Apiari',
  contact_docs:'📄 Documenti App',
  contact_tech_card:'Scheda Tecnica', contact_tech_card_sub:'Specifiche e funzionalità',
  contact_user_guide:'Guida Utente', contact_user_guide_sub:'Guida completa a tutte le funzioni',
  contact_support:'🛠️ Supporto Tecnico — Contattaci',
  contact_buy_title:'🛒 Acquista Licenza NectarOS',

  bn_dashboard:'Home', bn_hives:'Arnie',
  bn_apiaries:'Apiari', bn_ai:'IA', bn_more:'Altro',

  lang_select:'Seleziona la tua lingua', lang_current:'Lingua corrente',
},

/* ─────────────────────────────────────────────────────────────
   🇳🇱  NEDERLANDS
───────────────────────────────────────────────────────────── */
nl: {
  _dir:'ltr', _name:'Nederlands', _flag:'🇳🇱',

  app_name:'NectarOS', app_sub:'Intelligent Bijenstal Beheersysteem',
  loading:'Laden',

  update_available:'🎉 Nieuwe versie beschikbaar — tik om bij te werken',
  update_safe:'Uw gegevens zijn veilig bewaard',
  update_btn:'⬆️ Bijwerken',

  lic_title:'NectarOS', lic_sub:'Licentiesysteem',
  lic_tab_trial:'⏱️ Proef', lic_tab_activate:'🔑 Activeren', lic_tab_devices:'📱 Apparaten',
  lic_extend_trial:'⏳ Proefperiode met 15 dagen verlengen',
  lic_enter_app:'🐝 App betreden',
  lic_device_hint:'🔑 Uw apparaat-ID (stuur het naar de ontwikkelaar voor uw code)',
  lic_copy_device:'📋 Apparaat-ID kopiëren',
  lic_serial_label:'Voer de activeringscode in (Serie)',
  lic_serial_placeholder:'XXXX-XXXX-XXXX-XXXX',
  lic_activate_btn:'✅ Licentie activeren',
  lic_buy_title:'🛒 Hoe koop ik een licentie?',
  lic_buy_step1:'Kopieer uw apparaat-ID hierboven',
  lic_buy_step2:'Stuur het met betaling via een van de onderstaande methoden',
  lic_buy_step3:'U ontvangt uw activeringscode binnen 24 uur',
  lic_wa_btn:'💬 Neem contact met ons op via WhatsApp',
  lic_wa_hint:'Stuur uw apparaat-ID en betalingsbewijs om uw licentie te activeren',

  trial_active:'Proef Actief', trial_expired:'Verlopen',
  trial_days_left:'dagen resterend', trial_total_days:'totale dagen',
  trial_extension:'Verlenging',
  trial_almost_up:'De tijd loopt op!',
  trial_few_days:'Nog maar weinig dagen',
  trial_mode:'Proefmodus',
  trial_elapsed:'verstreken',
  trial_of:'van',
  trial_activate_now:'⚡ Activeer uw licentie voor het verstrijken',
  trial_data_safe:'Uw gegevens zijn veilig en worden automatisch overgedragen',
  trial_used:'Gebruikt', trial_available:'Beschikbaar',
  trial_ended_title:'Proefperiode beëindigd!',
  trial_ended_sub:'U heeft %d dagen van NectarOS proef genoten\nActiveer uw licentie om door te gaan',
  trial_data_warning:'⚠️ Uw gegevens zijn in gevaar',
  trial_data_warning_sub:'Uw gegevens zijn lokaal opgeslagen — ze worden niet verwijderd, maar zonder licentie heeft u geen toegang',
  trial_enter_expired:'🔒 Proef Beëindigd',
  trial_enter_trial:'🐝 App betreden (Proef)',

  login_title:'Aanmelden',
  login_user:'Gebruikersnaam', login_pass:'Wachtwoord',
  login_btn:'🔓 Aanmelden',

  nav_main:'Hoofd', nav_bee_health:'Bijensgezondheid',
  nav_equipment:'Uitrusting & Opslag', nav_commerce:'Handel',
  nav_finance_rep:'Financiële Rapporten', nav_ai_section:'Kunstmatige Intelligentie',
  nav_analytics:'Analyse & Planning', nav_monitoring:'Monitoring & Veld',
  nav_resources:'Bronnen & Kennis', nav_personal:'Persoonlijk Beheer',
  nav_operations:'Geavanceerde Operaties', nav_system:'Systeem',

  nav_dashboard:'Dashboard', nav_apiaries:'Bijenhouderijen',
  nav_map:'Interactieve Kaart', nav_advanced:'Geavanceerde Statistieken',
  nav_hives:'Bijenkorven', nav_calendar:'Kalender',
  nav_inspections:'Inspectielogboek', nav_treatments:'Behandelingen',
  nav_weights:'Gewichtslogboek', nav_harvest:'Oogstlogboek',
  nav_batches:'Productiebatches', nav_queens:'Koningingen-genetica',
  nav_health:'Gezondheidscertificaten', nav_assets:'Barcodes',
  nav_inventory:'Inventaris', nav_store:'Winkel',
  nav_crm:'Klanten', nav_sales:'Verkoop',
  nav_expenses:'Uitgaven', nav_profit:'Winst',
  nav_finance:'Financiële Rapporten', nav_settings:'Instellingen',
  nav_ai:'Kunstmatige Intelligentie', nav_aiplus:'KI+ Geavanceerd',
  nav_contact:'Neem contact op', nav_goals:'Productiedoelen',
  nav_seasonal:'Seizoensplanning', nav_radar:'Bijenkorf Vergelijking',
  nav_compare:'Jaarlijkse vergelijking', nav_advstats:'Geavanceerde Statistieken',
  nav_losses:'Verliesanalyse', nav_annual:'Jaarrapport',
  nav_weather:'Bijenhouderij Weer', nav_tempmon:'Temperatuurmonitor',
  nav_fieldmode:'Veldmodus', nav_scanner:'Barcodescanner',
  nav_foragemap:'Weidkaart', nav_plants:'Bijenplanten',
  nav_disease:'Ziektehandleiding', nav_calcs:'Rekenmachines',
  nav_honeylabs:'Honiglaboratorium', nav_notifs:'Herinneringen',
  nav_pushnotifs:'Telefoonmeldingen', nav_tasks:'Wekelijkse Taken',
  nav_journal:'Dagelijks Dagboek', nav_achievements:'Prestaties',
  nav_orders:'Bestellingen & Verzending', nav_invoice:'Facturen',
  nav_wareport:'WhatsApp Rapport', nav_team:'Werkteam',
  nav_integrations:'Integraties', nav_themes:'Thema\'s & Uiterlijk',
  nav_security:'Beveiliging & Privacy', nav_logout:'Uitloggen',

  scr_dashboard:'Dashboard', scr_apiaries:'Bijenhouderijen',
  scr_hives:'Bijenkorven', scr_calendar:'Kalender',
  scr_inspections:'Inspecties', scr_treatments:'Behandelingen',
  scr_weights:'Gewichten', scr_harvest:'Oogst',
  scr_queens:'Koninginnen', scr_health:'Certificaten',
  scr_assets:'Uitrusting', scr_inventory:'Inventaris',
  scr_store:'Winkel', scr_crm:'Klanten',
  scr_sales:'Verkoop', scr_expenses:'Uitgaven',
  scr_profit:'Winst', scr_finance:'Rapporten',
  scr_settings:'Instellingen', scr_ai:'Kunstmatige Intelligentie',
  scr_contact:'Neem contact op', scr_plants:'Planten',
  scr_disease:'Ziekten', scr_calcs:'Rekenmachines',
  scr_weather:'Weer', scr_security:'Beveiliging',
  scr_themes:'Thema\'s', scr_scanner:'Barcodescanner',

  btn_add:'➕ Toevoegen', btn_save:'💾 Opslaan', btn_cancel:'Annuleren',
  btn_delete:'🗑️ Verwijderen', btn_edit:'✏️ Bewerken', btn_close:'✕ Sluiten',
  btn_copy:'📋 Kopiëren', btn_share:'📤 Delen',
  btn_export:'📤 Exporteren', btn_import:'📥 Importeren',
  btn_backup:'💾 Back-up', btn_refresh:'🔄 Vernieuwen',
  btn_search:'🔍 Zoeken', btn_filter:'🔽 Filteren',
  btn_send:'📤 Verzenden', btn_print:'🖨️ Afdrukken',
  btn_confirm:'✅ Bevestigen', btn_yes:'Ja', btn_no:'Nee',
  btn_ok:'OK', btn_back:'← Terug',
  btn_activate:'Activeren', btn_deactivate:'Deactiveren',
  btn_more:'Meer',

  lbl_name:'Naam', lbl_date:'Datum',
  lbl_notes:'Notities', lbl_status:'Status',
  lbl_type:'Type', lbl_quantity:'Hoeveelheid',
  lbl_price:'Prijs', lbl_total:'Totaal',
  lbl_weight:'Gewicht', lbl_location:'Locatie',
  lbl_phone:'Telefoon', lbl_email:'E-mail',
  lbl_address:'Adres', lbl_description:'Beschrijving',
  lbl_active:'Actief', lbl_inactive:'Inactief',
  lbl_all:'Alle', lbl_none:'Geen',
  lbl_loading:'Laden...', lbl_no_data:'Geen gegevens beschikbaar',
  lbl_error:'Fout', lbl_success:'Succes',
  lbl_warning:'Waarschuwing',

  contact_title:'📬 Neem contact op', contact_sub:'Intelligent Bijenstal Beheersysteem',
  contact_docs:'📄 App Documenten',
  contact_tech_card:'Technisch Blad', contact_tech_card_sub:'App specificaties',
  contact_user_guide:'Gebruikershandleiding', contact_user_guide_sub:'Volledige gids voor alle functies',
  contact_support:'🛠️ Technische Ondersteuning — Neem contact op',
  contact_buy_title:'🛒 Koop NectarOS Licentie',

  bn_dashboard:'Home', bn_hives:'Bijenkorven',
  bn_apiaries:'Bijenhouderijen', bn_ai:'KI', bn_more:'Meer',

  lang_select:'Selecteer uw taal', lang_current:'Huidige taal',
},

}; // end NECTAR_LANGS


/* ═══════════════════════════════════════════════════════════════
   i18n ENGINE
═══════════════════════════════════════════════════════════════ */

const I18N = {

  /* ── الحالة ── */
  current: 'ar',
  _data: null,

  /* ── تهيئة ── */
  init(){
    const saved = localStorage.getItem('_nec_lang') || 'ar';
    this.apply(saved, false);
  },

  /* ── الترجمة الفورية ── */
  t(key, ...args){
    const d = this._data || NECTAR_LANGS.ar;
    let str = d[key] || NECTAR_LANGS.ar[key] || key;
    // استبدال %d بالأرقام
    args.forEach(a => { str = str.replace('%d', a); });
    return str;
  },

  /* ── تطبيق اللغة ── */
  apply(lang, save = true){
    if(!NECTAR_LANGS[lang]) lang = 'ar';
    this.current = lang;
    this._data   = NECTAR_LANGS[lang];
    const dir    = this._data._dir || 'rtl';

    if(save) localStorage.setItem('_nec_lang', lang);

    /* اتجاه الصفحة */
    document.documentElement.lang = lang;
    document.documentElement.dir  = dir;
    document.documentElement.setAttribute('data-lang', lang);

    /* ترجمة كل عناصر data-i18n */
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      const val = this.t(key);
      if(el.tagName === 'INPUT' || el.tagName === 'TEXTAREA'){
        el.placeholder = val;
      } else {
        el.textContent = val;
      }
    });

    /* تحديث أزرار البناف بار السفلي */
    const bnMap = {
      'bn-dashboard':'bn_dashboard','bn-hives':'bn_hives',
      'bn-apiaries':'bn_apiaries','bn-ai':'bn_ai','bn-more':'bn_more'
    };
    Object.entries(bnMap).forEach(([id, key]) => {
      const el = document.querySelector(`#${id} .bn-label`);
      if(el) el.textContent = this.t(key);
    });

    /* تحديث عناصر القائمة الجانبية */
    document.querySelectorAll('[data-i18n-nav]').forEach(el => {
      const key = el.getAttribute('data-i18n-nav');
      el.textContent = this.t(key);
    });

    /* إطلاق حدث للتطبيق */
    window.dispatchEvent(new CustomEvent('langchange', { detail: { lang, dir } }));
  },

  /* ── قائمة اللغات ── */
  getList(){
    return Object.entries(NECTAR_LANGS).map(([code, d]) => ({
      code, name: d._name, flag: d._flag, dir: d._dir
    }));
  },

};

/* ── تشغيل تلقائي عند تحميل الملف ── */
if(document.readyState === 'loading'){
  document.addEventListener('DOMContentLoaded', () => I18N.init());
} else {
  I18N.init();
}

/* ── تصدير عالمي ── */
window.I18N = I18N;
window.__ = (key, ...args) => I18N.t(key, ...args);
